### ISSUE TITLE
Improvements for various equations with large braces

### ISSUE THREAD

**Issue by plaes** [uvm-plaid/programming-dp#18]
Equation (2) in [chapter 3 - Laplace Mechanism](https://programming-dp.com/notebooks/ch3.html#the-laplace-mechanism) should use `\left` and `\right` for braces on the right side:
```latex
\begin{equation}
F(x) = f(x) + \textsf{Lap}\left(\frac{s}{\epsilon}\right)
\end{equation}
```
Before:
![image](https://user-images.githubusercontent.com/91895/146252769-2cd1be16-f5a1-4c1e-bdb9-f5f25f94896b.png)
After:
![image](https://user-images.githubusercontent.com/91895/146252842-3f7d73ca-1e70-41b7-843e-d98d038c684d.png)

There are also other equations which would look a lot better if the `\left` and `\right` were used for braces:
* Chapter 5 - equation 3
* Chapter 7 - equation 18
* Chapter 8 - eq 22, 23, 25
* Chapter 9 - eq 30, 31, 32
* Chapter 13 - eq 38

**Comment by jnear** [comment]
Thank you!!
