### ISSUE TITLE
Clipped Gradient Equation Incorrect

### ISSUE THREAD

**Issue by ez2rok** [uvm-plaid/programming-dp#19]
Hi. In equation 36 of the Machine Learning Section of the book and the subsequent paragraph, the clipped gradient is written as

![\begin{align}
   || \text{L2_clip}(\nabla(\theta; X, y), b) - \text{clip}(\nabla(\theta; X \text{'}, y))||
\end{align}](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%7D%0A+++%7C%7C+%5Ctext%7BL2_clip%7D%28%5Cnabla%28%5Ctheta%3B+X%2C+y%29%2C+b%29+-+%5Ctext%7Bclip%7D%28%5Cnabla%28%5Ctheta%3B+X+%5Ctext%7B%27%7D%2C+y%29%29%7C%7C%0A%5Cend%7Balign%7D)

when it really should be written as 

![\begin{align}
   || \text{L2_clip}(\nabla(\theta; X, y), b) - \text{clip}(\nabla(\theta; X \text{'}, y), 0)||
\end{align}](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%7D%0A+++%7C%7C+%5Ctext%7BL2_clip%7D%28%5Cnabla%28%5Ctheta%3B+X%2C+y%29%2C+b%29+-+%5Ctext%7Bclip%7D%28%5Cnabla%28%5Ctheta%3B+X+%5Ctext%7B%27%7D%2C+y%29%2C+0%29%7C%7C%0A%5Cend%7Balign%7D)

The second term is missing a zero.

(I wrote this latex in this github issue using [this](https://gist.github.com/a-rodin/fef3f543412d6e1ec5b6cf55bf197d7b) trick here.)

**Comment by jnear** [comment]
Thank you!!
