### ISSUE TITLE
Issue on page /ch1.html

### ISSUE THREAD

**Issue by mjdominus-ly** [uvm-plaid/programming-dp#35]
There is a display of three records just prior to the text:

> This time, there are three rows returned - and we don’t know which one is the real Karrie.

The three records have the same date of birth ("9/7/1967") but different ages.  This is impossible.

**Comment by mjdominus-ly** [comment]
And, I should add, I found it confusing, because I thought perhaps there was something subtle going on that I did not appreciate.

**Comment by chikeabuah** [comment]
Fixed!
