### ISSUE TITLE
Gaussian mechanism formula is not valid for every epsilon / delta

### ISSUE THREAD

**Issue by csharrison** [uvm-plaid/programming-dp#45]
The formula $\sigma^2 = 2 s^2 ln(1.25/\delta) /  \epsilon^2$ is not valid for every epsilon / delta. Theorem 3.22 in Dwork, Roth is only for $\epsilon \in (0, 1)$. See theorem 4 in [Balle et al (2018)](https://proceedings.mlr.press/v80/balle18a/balle18a.pdf) showing this bound does not hold for $\epsilon > 1$.

It would probably be good to add a caveat that the bounds in the book are not valid for every $\epsilon$, in a footnote or something.

**Comment by chikeabuah** [comment]
@csharrison thank you for your observation! I have amended the book with Balle et al's contribution: https://github.com/uvm-plaid/programming-dp/commit/fcbbef89991d8dc17611ec9d7948f1305cfeeee8
